package semjon00.meteorbeddestroyer.mixin;

import net.minecraft.client.network.ClientPlayNetworkHandler;
import net.minecraft.network.Packet;
import net.minecraft.network.packet.c2s.play.PlayerActionC2SPacket;
import net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

import java.util.ArrayList;
import java.util.List;

import static semjon00.meteorbeddestroyer.MeteorBedDestroyerAddon.debugLog;
import static semjon00.meteorbeddestroyer.MeteorBedDestroyerAddon.shouldDebug;

@Mixin(ClientPlayNetworkHandler.class)
public class ClientPlayNetworkHandlerMixin {
    // Debug mixin for verifying that what we send pleases the server
    @Inject(method = "sendPacket", at = @At("HEAD"))
    private void sendPacket(Packet<?> packet, CallbackInfo ci) {
//        if (!shouldDebug) return;
//        float DEFAULT = 8.14634512354656529841256f; // Generated by giving the number row on the keyboard a good roll
//        if (packet instanceof PlayerActionC2SPacket p) {
//            debugLog("packet PlayerAction {} {} {}", p.getPos(), p.getAction(), p.getDirection());
//        } else if (packet instanceof PlayerMoveC2SPacket p) {
//            List<String> ls = new ArrayList<>();
//            if (p.changesPosition()) ls.add(
//                    "%s/%s/%s".formatted(p.getX(DEFAULT), p.getY(DEFAULT), p.getZ(DEFAULT)));
//            if (p.changesLook()) ls.add(
//                    "%s:%s".formatted(p.getYaw(DEFAULT), p.getPitch(DEFAULT)));
//            ls.add(String.valueOf(p.isOnGround()));
//
//            debugLog("packet PlayerMove {}", ls);
//        }
    }
}
